export const MAX_ROWS_PER_FIRST_PAGE_BEFORE_PAGINATION = 20;
export const MAX_ROWS_PER_FIRST_PAGE_AFTER_PAGINATION = 25;
export const MAX_ROWS_PER_OTHER_PAGES_BEFORE_PAGINATION = 35;
export const MAX_ROWS_PER_OTHER_PAGES_AFTER_PAGINATION = 40;
